export default {
  logo: require("../assets/images/logo.png"),
  hideEye: require("../assets/images/hide.png"),
  showEye: require("../assets/images/show.png"),
  home: require("../assets/images/home.png"),
  nearby: require('../assets/images/nearby.png'),
  booking: require('../assets/images/booking.png'),
  profile: require('../assets/images/profile.png'),
  notification: require('../assets/images/notification.png'),
  search: require('../assets/images/search.png'),
  mic: require('../assets/images/mic.png'),
  salonpic:require('../assets/images/salonpic.jpg'),
  salonpic2:require('../assets/images/salonpic2.jpg'),
  hairsalon:require('../assets/images/hairsalon.png'),
  nailsalon:require('../assets/images/nailsalon.png'),
  makeup:require('../assets/images/makeup.png'),
  skincare:require('../assets/images/skincare.png'),
  spa:require('../assets/images/spa.jpg'),
  homeservice:require('../assets/images/homeservice.png'),

};