export default {
  SIGNIN: "Signin",
  SIGNUP: "Signup",
  FORGOTPASSWORD: "ForgotPassword",
  HOME: "Home",
  CODEVERIFICATION: "CodeVerification",
  CHANGEPASSWORD: "ChangePassword",
  TABROUTES: "TabRoutes",
  HOME: "Home",
  NEARBY: "NearBy",
  BOOKING: "Booking",
  PROFILE: "Profile",
  NOTIFICATION: "Notification",
  SHOP: "Shop",
    CATEGORIES: "Categories",
  SERVICES: "Services",
  INFORMATION: "Information",
  REVIEWS: "Reviews",
  TOPTAB: "TopTab",
  MYACCONT: "MyAccount",
  STEPPERFORMSCREEN:"StepperFormScreen",
  AUTHSTACK:"AuthStack",
  REVIEWS:"Reviews"
};
